"""Add column priority

Revision ID: fadc8987ee72
Revises: f7b6a0868fd4
Create Date: 2022-07-15 11:59:13.136798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadc8987ee72'
down_revision = 'f7b6a0868fd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'priority')
    # ### end Alembic commands ###
