"""Fix column priority

Revision ID: 837420a978f2
Revises: fadc8987ee72
Create Date: 2022-07-15 12:01:02.666407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837420a978f2'
down_revision = 'fadc8987ee72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.drop_column('users', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
